version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: siddhartha3004/vprofiledb 
    container_name: vprodb 
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/sql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
  vprocache01: 
    image: memcached
    ports:
      - "11211:11211"
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER="guest"
      - RABBITMQ_DEFAULT_PASSWORD="guest"
  vproapp:
    build: 
      context: ./Docker-files/app
    image: siddhartha3004/vprofileapp 
    container_name: vproapp 
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  vproweb:
    build:
      context: ./Docker-files/web
    image: siddhartha3004/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
volumes:
  vproappdata: {}
  vprodbdata: {}

  

            

  
